[package]
name = "libm8s"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
log = "0.4"
indexmap = { version = "2.5", features = ["serde"] }
schemars = { version = "0.8", features = ["indexmap2"] }
