[package]
name = "libm8s"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
indexmap = { version = "2.5", features = ["serde"] }
